// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXK6tpphtBKcuDGwcZnuHZyhdMhRF8Gfg',
    appId: '1:1021002981605:android:d001b29bcd56136bef340c',
    messagingSenderId: '1021002981605',
    projectId: 'barberapp-c951e',
    storageBucket: 'barberapp-c951e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dpXEM6H2SW-hBupVIYtA8vfQd1aZ_RM',
    appId: '1:1021002981605:ios:1be14ba225d95cc6ef340c',
    messagingSenderId: '1021002981605',
    projectId: 'barberapp-c951e',
    storageBucket: 'barberapp-c951e.appspot.com',
    iosBundleId: 'com.kmy.barberApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJut1LdCK-zDJt9kaQSfkltkIduJhUSw',
    appId: '1:1021002981605:web:1dd6871b06f9727aef340c',
    messagingSenderId: '1021002981605',
    projectId: 'barberapp-c951e',
    authDomain: 'barberapp-c951e.firebaseapp.com',
    storageBucket: 'barberapp-c951e.appspot.com',
    measurementId: 'G-7WYR8DFZ8C',
  );

}